### ISSUE TITLE
decimal part of AI2!

### ISSUE THREAD

**Issue by unixfx** [TypesettingTools/AI2ASS#4]
Hi.
Actually is there any way to remove decimal part of shape code
example (417.78) I want it without "." like this "417"
so is it possible ?

thank you.

**Comment by torque** [comment]
Making that change would require modifying the code, but there's more to it than that.

The problem is a truncation or even rounding policy for ensuring the output coordinates are integers loses a lot of precision, which ends up making the shapes look wrong, either subtly or obviously. I'm aware that ass has `{\p2}`, `{\p3}`, etc, for increasing the precision of shapes, but I think that's a bad and awkward way to go about solving this problem.

Decimal shape coordinates have been supported in xy-vsfilter and libass since, I think, 2013 or so. I don't see a reason to support this use case.

Why do you need to remove the decimal part of the coordinates?

**Comment by unixfx** [comment]
Actually AssDraw not supported decimal part of code, so I was looking for something or If can modify the code (script). 
I don't prefer decimal part of shape code, it's increase the size of ass file a little bit & AssDraw  not supported that =)

thanx

**Comment by Youka** [comment]
`Shape:gsub("(%-?%d+)%.?%d*", "%1")`
No rounding but what you want ("remove decimal part") in a fast way.

Instead of `math.ceil` maybe you wanted `math.floor(number + 0.5)` for rounding?

**Comment by unixfx** [comment]
Yes, I want to remove decimal part.

**Comment by torque** [comment]
I have no interest in supporting ASSDraw, an ancient and really janky tool. You're welcome to write whatever scripts you want to perform whatever conversions you want outside of AI2ASS.

**Comment by line0** [comment]
Amen.
