### ISSUE TITLE
Gradient

### ISSUE THREAD

**Issue by bebetoalves** [TypesettingTools/AI2ASS#8]
Is it possible I export the gradient applied in the text?
I'm exporting the common way, and the gradient doesn't come either.

Print 1: https://i.imgur.com/kgB26iE.png
Print 2: https://i.imgur.com/IQC03vu.png

**Comment by torque** [comment]
For this case, your 3-stop linear gradient could be trivially produced in directly in ASS using one of the existing gradient automation scripts, like [gradient everything](https://github.com/TypesettingTools/lyger-Aegisub-Scripts/blob/master/macros/lyger.GradientEverything.moon). However, it's possible to create gradients in AI that can't be trivially produced with an existing script.

Last I looked at it, Illustrator's JS API was garbage with gradients, which is why AI2ASS doesn't support them directly. There's some technique for slicing lines up by gradient in AI and then exporting the results, but I don't know what that process is.

**Comment by SchRita** [comment]
Hi @bebetoalves , please see [this tutorial](https://typesettingtools.github.io/2019/03/23/gradients-with-illustrator.html) of line0 on this topic.
